services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cmd/web/config.json:/app/cmd/web/config.json
      - ./tls:/app/tls
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: movie_trailers
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
#so as of now, db is working and good.
#Can connect but on windows must use - docker exec -it my-movie-db mysql -u user -p 
#where the 'my-movie-db part is the container name shown when you do docker ps
#and then enter the password 'password' when prompted.

#currently there is no schema set up
#also to stop, docker compose down

#To run the migration - migrate -path db/migrations -database "mysql://user:password@tcp(localhost:3306)/movie_trailers" up
#down to downgrade it

  migrate:
      image: migrate/migrate
      volumes:
        - ./db/migrations:/migrations
      command: ["-path", "/migrations", "-database", "mysql://user:password@tcp(db:3306)/movie_trailers", "up"]
      depends_on:
        - db

volumes:
  db_data: